### ISSUE TITLE
export-api-def: Inconsistency between id's type in method argument and model property?

### ISSUE THREAD

**Issue by hideya** [strongloop/generator-loopback#142]
While trying out `slc loopback:export-api-def` and [swagger codegen](https://github.com/swagger-api/swagger-codegen) to generate client side SDKs, I noticed that attributes for `id` property of models is like:
```
      id:
        type: number
        format: double
``` 
whereas `id` argument for method invocations looks like the following:
```
      operationId: User.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
```
This `id`'s type inconsistency between `number` and `string` results in the same inconsistency in the generated SDKs, i.e. we need to cast `model.id` to `string` to give it as the argument e.g. for `findById`.  Shouldn't this this inconsistency be resolved?
