### ISSUE TITLE
Using the generator to create a non-required date sets an invalid default value of `null`

### ISSUE THREAD

**Issue by samt** [strongloop/generator-loopback#224]
Example:

```
? Enter the model name: docnull
? Select the data-source to attach docnull to: docnull (memory)
? Select model's base class PersistedModel
? Expose docnull via the REST API? Yes
? Custom plural form (used to build REST URL): 
? Common model or server only? common
Let's add some docnull properties now.

Enter an empty property name when done.
? Property name: date
   invoke   loopback:property
? Property type: date
? Required? No
? Default value[leave blank for none]: 

Let's add another docnull property.
Enter an empty property name when done.
? Property name: 
Done running LoopBack generator
```

Results in the following (excerpt) in the yaml:
```yaml
# ...
definitions:
  docnull:
    properties:
      date:
        default: null
        type: string
        format: date
      id:
        type: number
        format: double
    additionalProperties: false
  x-any:
    properties: {}
# ...
```
As null is an invalid value for a `date` type, it will fail validation is the field is omitted.
